name: event2.ourworld.tf
on:
  push:
    branch: [ development ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: pushing latest change on event2.ourworld.tf
      uses: appleboy/ssh-action@master
      with:
        host: event2.ourworld.tf
        username: webuser
        key: ${{ secrets.TF_SECRET }}
        port: 34022
        script: |
          cd /home/webuser/websites/www2/www_ourworld_ictc
          git log -1
          git pull
          systemctl --user restart event2-ourworldtf.service
